Support recent upstream changes
metabrainz/musicbrainz-docker pull request #37
Opened 2017-04-13 18:15 UTC by pdf

Bump server version to v-2017-03-27

2017-04-18 10:17 UTC, pdf commented
Updated the test script with a valid asset path to allow the build to pass.  Out of curiosity, is there a reason for compiling assets on every startup rather than as a docker build step?

2017-04-18 22:34 UTC, jsturgis commented
Thanks for the PR, I am working on running compile_resources.sh at build time instead of at runtime.

2017-04-18 23:53 UTC, pdf commented
Since it calls perl, it probably needs `eval $( perl -Mlocal::lib)` to populate the env before running it.  The method I used to run `cpanm` in the Dockerfile appears to do the job.

Would you like me to update this PR with that change?

2017-04-19 19:44 UTC, jsturgis requested changes

2017-04-19 19:44 UTC, jsturgis commented on musicbrainz-dockerfile/DBDefs.pm
> +        host        => "db",
is there a reason that you are using a hardcoded host and port value instead of using the env variables?

2017-04-19 19:49 UTC, pdf commented on musicbrainz-dockerfile/DBDefs.pm
> +        host        => "db",
Use of env vars to connect to linked services is [deprecated](https://docs.docker.com/compose/link-env-deprecated/), and it's now recommended to just use the link name directly.

2017-04-19 19:50 UTC, jsturgis commented on musicbrainz-dockerfile/DBDefs.pm
> +        host        => "db",
I see thanks for the info, is there a doc you can point me to with more details on this?

2017-04-19 19:50 UTC, jsturgis commented on musicbrainz-dockerfile/DBDefs.pm
> +        host        => "db",
ok cool thanks for the info.

2017-04-19 20:03 UTC, jsturgis approved these changes

2017-04-19 20:03 UTC, merged