Allow setting Postgres version via build-time argument
metabrainz/musicbrainz-docker pull request #89
Opened 2018-11-28 19:40 UTC by LeoVerto

This PR allows setting the postgres version in it's dockerfile by using the `POSTGRES_VERSION` build-time argument (note `PG_VERSION` would collide with env vars of the parent image). The default is set to 9.5 as to not break workflows of users using the image directly.

It also makes use of the arg in the compose file where the version can easily be changed. Using the `image` option is necessary to force rebuilds on arg changes and makes switching between versions easier.

While this setup is very backwards-compatible, updating the postgres version would require changing it in all three places (although changing the Dockerfile is not strictly required). A build script or .env file could further optimize this.

2018-11-30 11:19 UTC, mayhem reviewed
Looks ok to me, but I'm guessing that somewhere the postgres client gets installed as well -- that would need to have the matching version installed, no?

2018-11-30 17:10 UTC, LeoVerto commented
If you mean the postgres client inside the container: the correct version is already included in the `postgres` base version:
```
$ docker run -it --rm musicbrainz-docker_db:10 sh
# psql --version
psql (PostgreSQL) 10.6 (Debian 10.6-1.pgdg90+1).
```

2018-12-03 11:40 UTC, mayhem commented
OK, great. Thanks!

2018-12-13 09:30 UTC, yvanzo requested changes
Would be nice to allow setting PostgreSQL version from `docker-compose` command-line without having to hack into the compose file. Also, can you please document this option into the README.md doc?

2019-01-28 07:56 UTC, yvanzo commented
Potential issue to look into: `psql` is installed in `musicbrainz` service too. It is used for maintenance and development mostly.

2019-02-05 17:23 UTC, yvanzo commented
Update: migration to SIR will be made prior to address this issue, as SIR depends on PostgreSQL too.

2019-02-12 22:06 UTC, yvanzo commented
@LeoVerto: After all, SIR still requires more work before being shipped in there. Thus I rebased your PR on master and completed it with commits for: setting Postgres version just from environment, rebuilding `musicbrainz` service with the same version of Postgres, and adding a line in documentation. Please take a look at it, thanks!

2019-02-12 22:07 UTC, yvanzo approved these changes

2019-02-13 16:00 UTC, LeoVerto commented
Looks good to me, I didn't even know you could set default values for env vars in compose files like that!

I noticed you added the postgres package installation after the MBS one, does this mean that the MBS version is going to change more rarely than the PG one? Otherwise the other way around might be better for intermediate layer re-usability.

2019-02-15 11:20 UTC, yvanzo commented
Good catch, I focused on development use case but for mirroring you’re too right! Fixed in [`80a421a`](https://github.com/metabrainz/musicbrainz-docker/commit/80a421ab66e85847a521b732a4abecd8e9f45b1f#diff-906e5d52e79584e237931f661ae3ab8a).

2019-02-15 11:21 UTC, merged

2019-02-15 11:21 UTC, yvanzo commented
Thank you @LeoVerto !